dist: trusty
before_install:
  - npm install -g npm@latest
  - npm set progress=false
install:
  - npm install
language: node_js
node_js:
  - "7.5"
  - "6.9"
  - "4.7"
script: npm run test:ci
after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
  - export $(cat .to_export_back) &> /dev/null
  - ./node_modules/contentful-sdk-jsdoc/bin/release-ci.sh 
addons:
  sauce_connect: true
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
