dist: trusty
cache:
  directories:
    - "node_modules"
    - "~/.npm"
language: node_js
node_js:
  - "8"
  - "4.7"
script: npm run test:ci
after_success:
  - codecov
  - npm run semantic-release
addons:
  sauce_connect: true
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
