dist: trusty
install:
  - npm install
language: node_js
node_js:
  - "8"
  - "4.7"
script: npm run test:ci
after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
  - export $(cat .to_export_back) &> /dev/null
  - npm run semantic-release
addons:
  sauce_connect: true
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
