apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: contentful-management.js
  description: |
    JavaScript library for Contentful's Management API (node & browser)
  annotations:
    circleci.com/project-slug: github/contentful/contentful-management.js
    github.com/project-slug: contentful/contentful-management.js
    contentful.com/ci-alert-slack: prd-extensibility-bots
spec:
  type: library
  lifecycle: production
  owner: group:team-developer-experience
